spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stackoverflow
    username: admin
    password: SEB44
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    include: oauth

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
    show-sql: true

