spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stackoverflow
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a925091518A!
  profiles:
    include: oauth, email

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
    show-sql: true

